@startuml
class SymbolSign {
    +Scale
    +Rotation
}
class FontSymbol {
    +Name
    +UCS4
    +Spacing
    +Geometry
}
class Color {
    +Name
    +L
    +C
    +H
    +T
}
'Associations
FontSymbol -- SymbolSign


    ' ASSOCIATION SymbolSignSymbolAssoc =
    '   Symbol -- {1} FontSymbol;
    '   SymbolSign -- {0..*} SymbolSign;
    ' END SymbolSignSymbolAssoc;

    ' ASSOCIATION SymbolSignClipSymbolAssoc =
    '   ClipSymbol -- {0..1} FontSymbol;
    '   SymbolSign2 -- {0..*} SymbolSign;
    ' END SymbolSignClipSymbolAssoc;

    ' ASSOCIATION SymbolSignColorAssoc =
    '   Color -- {0..1} Color;
    '   SymbolSign -- {0..*} SymbolSign;
    ' END SymbolSignColorAssoc;



' class TextSign {}
' class Font {}
' class FontySymbol_Geometry {}
' class FontSymbolSurface {}
' class Pattern_Symbol {}
' class PolylineSign {}
' class LineStyle {}
' class LineStyle_Solid {}
' class LineStyle_Dashed {}
' class PolylineAttrs {}
' class DashRec {}
' class SurfaceSign {}
'Associations
'PolylineSignLineStyleAssoc
@enduml